### ISSUE TITLE
Unable to access previously saved doc

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-GitWriter#13]
https://github.com/SusanBrown/TestingPoetryJan2018

This repo is not coming up in the menu when I load https://cwrc-writer.cwrc.ca 
I tried replacing https in my browser with http and it made no difference.

I don't know if it is related but I have a hunch that it might be: it can't load any templates either. See screenshot.

Seems extremely slow.

![image](https://user-images.githubusercontent.com/545952/35117051-574eef74-fc5b-11e7-965f-240c7987bfb2.png)

**Comment by jchartrand** [comment]
Seems to be something to do with https/http, but strangely, only on one of Susan's computers, and not for any one else.  Will shelve in the icebox until other https/http issues have been resolved, hoping that fixes it.

**Comment by SusanBrown** [comment]
This does not happen to me on Dev now that https is in place. Closing issue.

**Comment by SusanBrown** [comment]
This problem has resurfaced with one of my student. 
The repo in question is megwils0n. The problem seems to have happened, based on her frantic slack messages to me, March 29 around 10:15 am. 
She got the same error message as I did (see image above).
Then she got this one after restarting her browser:
![image](https://user-images.githubusercontent.com/545952/38156315-07eff9dc-344b-11e8-9410-86f5a4810666.png)
She clicked on authenticate and got this: 
![image](https://user-images.githubusercontent.com/545952/38159049-f56292b0-346e-11e8-97f8-1073386e45eb.png)

**Comment by SusanBrown** [comment]
So, this is obviously not just a fluke, so the question is what to do about it. 

James, do you have any idea what would be going on? It seems clear that the app is no longer accessing the right github account, because both my student and I were definitely signed in and connected.  

What is it that triggers that first error message "Can't find the templates"? And why can it not even find the generic templates, let alone the ones that belong to me as a user?

**Comment by jchartrand** [comment]
She might have lost her connection to the internet, or the DAIR server was down or inaccessible (which happens occasionally), or the Github API might have been down (although that's pretty unlikely).  And so, the CWRC-WRiter couldn't get any information, including the list of templates.

Once she 'restarted' her browser that probably removed her Github token, which produced that message about needing to authenticate.

My best guess is that we need better error handling when GitHub can't be reached (either directly or though the DAIR proxy) for any reason (including that the end user lost their connection to the internet).

However, because this is a web app, like all web apps, there will times when people lose data.  An alternative is to try to use some combination of Local Storage (in the browser) and/or periodically auto-saving to Github (which has gotten a lot easier to do and there is almost certainly a library to help).

**Comment by SusanBrown** [comment]
Given that her problem replicated mine, I seriously doubt that this is a problem with github or the DAIR server, although perhaps that is an initial factor. The problem persisted on my iMac for months.

The difference between our experiences is that I did not even get the message about needing to authenticate. So there was really nothing for me to do at all. Would it work to add a button, when the initial error is generated, to allow people to reset their Github token, and add to the error message that they should try clearing their browser cache and cookies first?

And do you know what that 443 error from Github would be in response to clicking the authentication button?

I would think that autosaving to GitHub would be ideal if we can do that.





On Mar 31, 2018, at 8:05 AM, James Chartrand <notifications@github.com<mailto:notifications@github.com>> wrote:


She might have lost her connection to the internet, or the DAIR server was down or inaccessible (which happens occasionally), or the Github API might have been down (although that's pretty unlikely). And so, the CWRC-WRiter couldn't get any information, including the list of templates.

Once she 'restarted' her browser that probably removed her Github token, which produced that message about needing to authenticate.

My best guess is that we need better error handling when GitHub can't be reached (either directly or though the DAIR proxy) for any reason (including that the end user lost their connection to the internet).

However, because this is a web app, like all web apps, there will times when people lose data. An alternative is to try to use some combination of Local Storage (in the browser) and/or periodically auto-saving to Github (which has gotten a lot easier to do and there is almost certainly a library to help).

**Comment by jchartrand** [comment]
You are assuming that because the two problems appear at least somewhat similar, that they must therefore also have the same root cause.  And then conclude that her problem would, like yours, have therefore also continued for months, and so her problem can't be a connection issue. 

However, it is entirely possible that she had a different problem.  Yes, you may both have experienced similar results - nothing showing in your GitHub list or in the template list - but of course that doesn't mean they both had the same cause.   There are also two big differences -- your problem did seem to be cleared up by the https fix, and, as you point out, she had an authentication message that you didn't.

The getaddrinfo error, from what I can find, is often a problem with the DNS lookup (note that 443 is the port, not the error number).  And so, the error might suggest that the DAIR server couldn't resolve the GitHub.com name for whatever reason.  So, again, possibly a connection problem somewhere along the line.

**Comment by SusanBrown** [comment]
Yes, we may have had different problems. It is possible that I got the authentication button too but don't remember it, as it was so long ago.

Her problem was also solved by the https: fix, so at the very least we should put these steps into the troubleshooting section of the documentation, @ilovan. I'll make a separate ticket for autosaving to github.

**Comment by jchartrand** [comment]
Just so we all understand this, what do you mean by ‘her problem was also solved by the https fix’?  I thought she just had this problem in the last few days? We switched to https a month or more ago.  What https fix do you mean?

**Comment by SusanBrown** [comment]
No, I didn’t mean it was fixed by the switch to https://. I mean it was fixed by the same method as my problem: clearing cache and cookies and restarting machine and browser. (not sure if she restarted her machine). She initially partially cleared her browsing data and restarted the browser and it didn’t work.


On Apr 1, 2018, at 7:08 AM, James Chartrand <notifications@github.com<mailto:notifications@github.com>> wrote:

Just so we all understand this, what do you mean by ‘her problem was also solved by the https fix’? I thought she just had this problem in the last few days? We switched to https a month or more ago. What https fix do you mean?

**Comment by jchartrand** [comment]
I didn’t think clearing your cache, etc. actually did fix your problem?  I thought your problem dragged on for months for the same document?  I’m guessing you would have tried clearing the cache earlier.  I thought what at least seemed to fix it was finally switching the Git-Writer to use https, removing the http version entirely (i.e, what I meant by ‘https’ fix)?  I’m being annoyingly fussy here (and annoying even myself) because I think we need to be as clear as possible about these problems while they are somewhat fresh in our minds.

But, also, as you say, ‘she initially partially cleared her browsing data’, which strongly suggests (although it would be good to know what ‘partially’ means) that she got the authentication screen (please authenticate with GitHub) because she’d cleared her authentication details.  This is what should happen.  Probably, though, we should tell people up front that if they clear their cache they will remove their authentication details.  In fact, we should probably be telling people up front that we use cookies or local storage.  In some places I think it might now even be a legal requirement.  The Guelph or Alberta ethics people would I’m sure know. 

Also, though, I don’t think we can assume that clearing the cache, etc. really did fix the problem (the problem with no templates or files showing) in her case either.  We shouldn’t rule out the possibility that it was a network error (especially given that the DNS error seems to suggest as much).  And we should irregardless add better error handling for network problems (because there will inevitably be problems at some point), with nice messages to help the end user.

**Comment by ilovan** [comment]
@SusanBrown  - I think we should put the steps you mentioned in the troubleshooting document, but they should probably be described as steps to take to cover all possibilities if something doesn't work, not as a specific solution to a specific problem. I agree with @jchartrand that we still don't know what happened and presenting the steps you described as the solution could be misleading. Also, we need to keep things simple in troubleshooting, lest people would think doing it on their end is too complicated.

**Comment by SusanBrown** [comment]
Gitwriter is talking to the node.js server running on DAIR server. DAIR server in trying to connect with Github -- DNS lookup wasn't able to resolve call to github, couldn't get IP address. To resolve this would require talking to CANARIE and digging into the logs.

**Comment by ilovan** [comment]
@SusanBrown , do you want me to follow up with CANARIE re this now? I got the same "Could not find the templates" error on Thursday but  as I was also logged into the TAMU version I put it on that for the moment and then could not reproduce (not even when switching back and forward between the TAMU version and ours).

**Comment by SusanBrown** [comment]
Maybe worth asking them if there is anywhere that monitors the DAIR server that we could easily consult to see if there is a problem with the server when we run into this error, given that we are trying to figure out what is causing it.
